services:
  main:
    build: .  # 从当前目录名为Dockerfile的文件构建镜像,没有则忽略
    image: bus  # 构建的镜像名
    container_name: main
    volumes:
      - ./data/redis_cluster/7000:/root/data/redis_cluster/7000
      - ./data/redis_cluster/7001:/root/data/redis_cluster/7001
      - ./data/redis_cluster/7002:/root/data/redis_cluster/7002
      - ./data/redis_cluster/7003:/root/data/redis_cluster/7003
      - ./data/redis_cluster/7004:/root/data/redis_cluster/7004
      - ./data/redis_cluster/7005:/root/data/redis_cluster/7005
      - ./data/redis:/root/data/redis
    ports:
      - "7000:7000"  # HOST:CONTAINER应始终指定为带引号的字符串,以避免与yaml base-60 float发生冲突
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "6379:6379"   # redis
      - "80:80"
      - "7890:7890"  # clash
      - "9050:9050"  # tor
      - "8118:8118"  # privoxy
    networks:
      - bus_net
#    depends_on: # 只能保证容器启动和销毁顺序,不能确保依赖的容器是否ready
#      - mysql
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./cnf/mysql:/etc/mysql/conf.d  # mysql使用/etc/mysql/my.cnf和/etc/mysql/conf.d/*中的组合启动设置,后者优先级更高
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - bus_net
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./data/mongo:/data/db
      - ./cnf/mongo:/etc/mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - bus_net
    command: mongod -f /etc/mongo/mongod.conf

networks:
  bus_net:
    driver: bridge  # 默认就是bridge

