services:
  main:
    build: .
    image: bus
    container_name: main
    volumes:
      - ./data/redis_cluster/7000:/root/data/redis_cluster/7000
      - ./data/redis_cluster/7001:/root/data/redis_cluster/7001
      - ./data/redis_cluster/7002:/root/data/redis_cluster/7002
      - ./data/redis_cluster/7003:/root/data/redis_cluster/7003
      - ./data/redis_cluster/7004:/root/data/redis_cluster/7004
      - ./data/redis_cluster/7005:/root/data/redis_cluster/7005
      - ./data/redis:/root/data/redis
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "6379:6379"   # redis
      - "80:80"
    networks:
      - bus_net
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - bus_net
networks:
  bus_net:
    driver: bridge  # 默认就是bridge
#    command:
#      - supervisord
