services:
  bus:
    build: .
    image: bus
    container_name: bus_container
    volumes:
      - ./data/redis_cluster/7000:/root/data/redis_cluster/7000
      - ./data/redis_cluster/7001:/root/data/redis_cluster/7001
      - ./data/redis_cluster/7002:/root/data/redis_cluster/7002
      - ./data/redis_cluster/7003:/root/data/redis_cluster/7003
      - ./data/redis_cluster/7004:/root/data/redis_cluster/7004
      - ./data/redis_cluster/7005:/root/data/redis_cluster/7005
      - ./data/redis:/root/data/redis
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "6379:6379"   # redis
      - "80:80"
#    command:
#      - supervisord


